### ISSUE TITLE
Mod crashes on dedicated server

### ISSUE THREAD

**Issue by KazuMurako** [LegoMaster3650/Lunchbox#1]
Forge: 40.1.68
Lunchbox: 1.0.1
Minecraft: 1.18.2
Crash report: [crash-2023-01-18_04.57.14-fml.txt](https://github.com/LegoMaster3650/Lunchbox/files/10442286/crash-2023-01-18_04.57.14-fml.txt)
Will test with just Lunchbox and Forge and add a comment with additional details.

**Comment by KazuMurako** [comment]
Crash still happens with just Lunchbox and Forge on the server, no other mods.
Crash report: [crash-2023-01-18_05.12.22-fml.txt](https://github.com/LegoMaster3650/Lunchbox/files/10442355/crash-2023-01-18_05.12.22-fml.txt)

**Comment by LegoMaster3650** [comment]
Oh I see the issue here, update to [alpha 1.1.0](https://www.curseforge.com/minecraft/mc-mods/lunchboxes/files/3995569), as the mod has various server-related bugs on 1.0.1... Sorry for the confusion, but I marked it as alpha due to it being in the middle of an update I never got around to finishing yet for various reasons... (The server hotfix part is stable though!) Let me know if that solved your issue!

**Comment by KazuMurako** [comment]
Ah I see, I have alpha updates hidden in the curseforge client, so I didn't see that there was an update. I'll test it and get back to you.

**Comment by KazuMurako** [comment]
Server runs fine on the new version of the mod. I'll post the logs just in case, but the issue seems to fixed in the new version.
Log: [latest.log](https://github.com/LegoMaster3650/Lunchbox/files/10452387/latest.log)

**Comment by LegoMaster3650** [comment]
Great! Hopefully I can get the full mod update out eventually so this won't happen again... (it's colored lunchboxes, I'm being more creative than a simple recolor for this but I've been busy with other stuff)
